### ISSUE TITLE
Got artery_network-5, expected artery_network-4 

### ISSUE THREAD

**Issue by bitcoiners** [arterynetwork/artr#5]
getting errors like this while synchronizing blockchain

E[2021-04-16|16:03:40.705] dialing failed (attempts: 1): incompatible: peer is on a different network. Got artery_network-5, expected artery_network-4 module=pex addr=76ad3950e75773058ffdc2fa21199f991b34647b@185.52.58.220:26656

**Comment by mikluhamakuha** [comment]
Привет, тебе удалось поставить ноду?

**Comment by bitcoiners** [comment]
К сожелению пока нет. Синхронизация остановилась где то на 300,000+ блоке.

**Comment by Cryptoevil** [comment]
А долго синхронизация происходит?

**Comment by bitcoiners** [comment]
да, очень медленно, уже вторую неделю качает..

**Comment by mikluhamakuha** [comment]
Почему разработчики молчат? 
Проект как то поддерживается?

**Comment by bitcoiners** [comment]
Вопрос хороший. Я написал в службу поддержки по адресу - info@artery.network
Вот что мне ответили
"Здравствуйте. Извините, но поддержку Линукс мы не оказываем, все инструкции есть на Гитхаб."

**Comment by mikluhamakuha** [comment]
напиши свой контакт

**Comment by bitcoiners** [comment]
телеграм контакт - @slavixtube

**Comment by mikluhamakuha** [comment]
Пишу тебе в телеграм, не отвечаешь

**Comment by bitcoiners** [comment]
Не вижу.. Какой у тебя телеграм контакт?

**Comment by arterynetwork** [comment]
Здравствуйте. Да, после обновления на 1.3.0 правильный chain ID `artery_network-5`. Спасибо, что обратили на это наше внимание. Стартовать надо сразу с версии 1.3.0, генезис с правильным chain ID можно найти [здесь](https://artery.network/.well-known/genesis1.3.0.json). README мы только что поправили соответственно.

**Comment by investormsk** [comment]
@bitcoiners ответь в телеге пожалуйста ник @investormska
